os: Visual Studio 2017

version: "{build}-{branch}"

cache:
  - C:\Users\appveyor\.cargo
  - target

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - rustfmt --version

  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/Ortham/testing-plugins/archive/1.4.1.zip', "$env:APPVEYOR_BUILD_FOLDER\1.4.1.zip")
  - ps: 7z x "$env:APPVEYOR_BUILD_FOLDER\1.4.1.zip"
  - mv testing-plugins-1.4.1 testing-plugins

build: false

test_script:
  - cargo fmt --all -- --check
  # Run all tests and run the benchmarks once without measurement or analysis.
  - cargo bench --all --all-features -- --test

  # Need to rebuild the FFI wrapper so that its binary is given a filename
  # without a hash.
  - cargo build --manifest-path ffi/Cargo.toml --features ffi-headers
  - ps: mkdir ffi/build
  - cd ffi/build
  - cmake .. -G "Visual Studio 15 2017"
  - cmake --build .
  - ctest
