[book]
title = "Load orders in Elder Scrolls and Fallout games"
author = "Oliver Hamlet"
description = "Documentation describing how the load order systems in Bethesda's Elder Scrolls and Fallout games work."
